// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentDir():Promise<Array<string>>;

export function HandleFileClick():Promise<void>;

export function MoveDir(arg1:string):Promise<void>;

export function ReturnDirItems(arg1:Array<string>):Promise<string>;

export function SetStartingDir():Promise<void>;
